# This workflow runs the automated test and uploads the coverage results to codecov.io
# For more information see: https://github.com/codecov/codecov-action

name: "Run Codecov Tests"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  run-and-upload-coverage-report:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies and run coverage
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm ci
          touch css/custom.css
          npm run test:coverage
      - name: Upload coverage results to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
