name: "Electron Rebuild Testing"

on: [pull_request]

jobs:
  rebuild:
    name: Run electron-rebuild
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.18.1, 20.x, 22.x, 23.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install MagicMirror
        run: npm run install-mm
      - name: Install @electron/rebuild
        run: npm install @electron/rebuild
      - name: Install node-libgpiod deps
        run: sudo apt-get install gpiod libgpiod2 libgpiod-dev
      - name: Install test library (node-libgpiod) to be rebuilded
        run: npm install node-libgpiod
      - name: Run electron-rebuild
        run: npx electron-rebuild
        continue-on-error: false
